### ISSUE TITLE
Main body copy has no padding on mobile

### ISSUE THREAD

**Issue by luigimannoni** [qiazee/abraqiadabra#2]
On portrait mode the main copy of the website doesn't have a graceful padding on left and right side to make reading easier

![Screenshot_20190731-085643](https://user-images.githubusercontent.com/1405327/62194150-2b430680-b371-11e9-8d90-b350ca725e3d.jpg)

**Comment by qiazee** [comment]
Fixed in [1.1.0](https://github.com/qiazee/abraqiadabra/releases/tag/v1.1.0) with https://github.com/qiazee/abraqiadabra/commit/43b63e174e2592e7e66ccc611c2161dc259bc568

Changes are now live. Thanks for reporting this issue! 👍
